### PR TITLE
(Fix) disable finalize button in manage screen

### LINKED ISSUE #482: (Fix) Disable Finalize button in manage page, if crowdsale is not ended yet
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Sokol

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.poa.network/crowdsale/?addr=0x06f2fd58dD50591716166045Ff87086Ab20F2b75&networkID=77

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

No

---

### PR DESCRIPTION
**Pull request by fernandomg**
Closes #482

### CODE REVIEW

**Comment by vbaranov** [comment]
Fernando, resolve conflicts, please.

**Comment by vbaranov** [comment]
@fernandomg it is still enabled `/manage/0x06f2fd58dD50591716166045Ff87086Ab20F2b75` (Sokol POA)

**Comment by fernandomg** [comment]
@vbaranov I've been dealing with this issue, and I finally followed the approach that metamask is using (https://github.com/MetaMask/metamask-extension/blob/0fbecb9f7c3b4b0d0b885f6478db70625851f1c2/app/scripts/lib/tx-gas-utils.js#L19)

Metamask displays the message "Transaction Error. Exception thrown in contract code.", above the submit tx button.

It works fine in sokol. But in all the testnets that I tested it (local, rinkeby, kovan) it doesn't fail, and returns the amount of gas.

I couldn't test it in mainnet, so if you can give it a try in POA or mainnet, that would be really helpful.

**Comment by vbaranov** [comment]
@fernandomg I haven't tested it in any production chain yet. But I have faced another bug:

`/manage/0xeA3281B125D67911F6aB4DE8Da91b85B26ae7D86`

Crowdsale is updatable and had two tiers: 09/01/2018 - 11/01/2018 && 11/01/2018 - 14/01/2018

Chrome developer console log: [localhost-1516305261640.log](https://github.com/poanetwork/ico-wizard/files/1644243/localhost-1516305261640.log)


screen shot 2018-01-18 at 22 49 47

**Pull request merged**
