### PR TITLE
(Fix) Avoid duplicates in reserved tokens list

### LINKED ISSUE #441: (Feature) When reserving tokens, if the same address is input twice, replace the previous occurrence in the list
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

All

### If you were able to create it, what is the URL of your crowdsale?

No

### Do you have screenshots showing the problem?

No

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

No

---

### PR DESCRIPTION
**Pull request by fvictorio**
Closes #441.

If address already exists in the list of reserved tokens, it's replaced with the new value.

Should we do the same for the whitelist component?

### CODE REVIEW

**Comment by fvictorio** [comment]
Oh, that was intentional. I thought only one of the two options were allowed. I'll change that.

**Comment by fvictorio** [comment]
Fixed.

**Comment by fvictorio** [comment]
@vbaranov What bug do you mean? The behavior in the gif you shared is the expected one if I understood correctly.

**Comment by vbaranov** [comment]
@fvictorio I expected 7% and 1 token, as a final distribution. No?

**Comment by fvictorio** [comment]
Ohh, I see now. Thanks for clarifying.

**Comment by vbaranov** [comment]
Sure, anytime

**Comment by fvictorio** [comment]
@vbaranov fixed. Luckily, this also fixes #523.

**Pull request merged**
