### PR TITLE
(Fix)(Refactor) Deployment process refactor, mainnet problem resolving

### PR DESCRIPTION
**Pull request by vbaranov**
Closes https://github.com/poanetwork/ico-wizard/issues/472

Test crowdsale created in Sokol POA testnet with this patch: https://wizard.poa.network/crowdsale?addr=0x338f47C1AA1DBdB56DfEA17cc376C0b21f4fbDa2&networkID=77

**Problem**: 
- Deployment process fails on mainnet due to error event arising `Failed to check for transaction receipt` on one of the contract deployment, but in fact, transactions are successfully mined later.
- Gas estimation of contracts deployment uses old web3 implementation `web3.eth.estimateGas`
- Contract deployment and calling contracts' methods  have unclear implementation

**Solution** 
- Skip error `Failed to check for transaction receipt` https://github.com/poanetwork/ico-wizard/compare/deploy-refactor?#diff-26b560c26ff5c9bed28d8eccc79f8d83R162. We can skip it because transaction receipt will be created in any case, if a transaction will be alive in the blockchain and we'll read it in `receipt` event. If transaction won't reach a blockchain, I believe, it will be another type of error.
- Contract deployment and calling the methods of contract are derived from the base function: https://github.com/poanetwork/ico-wizard/compare/deploy-refactor?#diff-26b560c26ff5c9bed28d8eccc79f8d83R150
- Gas estimation for contract deployment http://web3js.readthedocs.io/en/1.0/web3-eth-contract.html?highlight=estimateGas#id11 is implemented
- Unified handling of sent transaction events
- Refactor callback hell
- Remove warning blocking crowdsale creation in mainnet

### CODE REVIEW

**Comment by fernandomg** [comment]
Got an Out of Gas error, when was about to register the crowdsale Address
https://github.com/poanetwork/ico-wizard/compare/deploy-refactor?#diff-26b560c26ff5c9bed28d8eccc79f8d83R251

https://etherscan.io/tx/0xba88fa4c7d3cfb3e63e5c6c01b49c850a857896705fb7247878b62c7c19f007f

[localhost-1515603544660.log](https://github.com/poanetwork/ico-wizard/files/1619763/localhost-1515603544660.log)

**Comment by fernandomg** [comment]
were you able to create an ICO? I'm still getting issues in the same step

**Comment by vbaranov** [comment]
@fernandomg 
I guess we should set an appropriate gas limit for this method https://github.com/poanetwork/ico-wizard/compare/deploy-refactor#diff-26b560c26ff5c9bed28d8eccc79f8d83R251, as we do for other methods of our wizard contracts. And it should work, I believe. I checked in Remix, that it should be ~ 65420 gas for this tx. How about gas limit 100000? What do you think?

**Comment by fernandomg** [comment]
@vbaranov It should be enough with 100000 (check here: https://etherscan.io/tx/0x33a20ac632bfe9cb1aa1e075043979c9635ba15a98197e1a1d4504258911fa3a)

BTW, I did a refactor, based on this branch (check branch: `deploy-refactor-review`).

- I removed all the `web3` object pass by reference
- Did the same as in other cases for tx and requested estimatedGas for `registerCrowdsaleAddress` (https://github.com/poanetwork/ico-wizard/blob/e5939c2492daae88f792a3e7dc15540328da00f7/src/utils/blockchainHelpers.js#L271)
- Fixed the promise pattern used in this refactor, instead of passing along `resolve` and `reject` functions I defined each step as a promise itself (https://github.com/poanetwork/ico-wizard/blob/e5939c2492daae88f792a3e7dc15540328da00f7/src/utils/blockchainHelpers.js#L142)

I tested locally and worked fine, but agains mainnet I had an error with `registerCrowdsaleAddress`.

Please, let me know if it works for you.

**Comment by vbaranov** [comment]
@fernandomg nice refactoring! I've merged `deploy-refactor-review` to current PR.
Also, 
- I've hardcoded gasLimit for function `registerCrowdsaleAddress` (https://github.com/poanetwork/ico-wizard/pull/476/files#diff-26b560c26ff5c9bed28d8eccc79f8d83R273), as we do for other methods, because of problems with gas estimation for contracts methods. It works for me.
- I've added avoiding of this error #480: https://github.com/poanetwork/ico-wizard/pull/476/files#diff-26b560c26ff5c9bed28d8eccc79f8d83R164
- I've refactored ternary operators: whitespaces are added to increase readability

I successfully created 1-tier crowdsale on mainnet: https://wizard.poa.network/crowdsale?addr=0xd5d83Ed6Dd24b759B331C49351EFe767f86Df45A&networkID=1
Total duration of creation: 2 hours 10 minutes (gas price: 35 Gwei)
Total log: [localhost-1515675287277.log](https://github.com/poanetwork/ico-wizard/files/1622636/localhost-1515675287277.log)

Please let me know, do you still have any issues with this PR in mainnet? I'll wait 2nd approvement to merge.

**Comment by fernandomg** [comment]
@vbaranov fantastic! I'm in the process of creating a crowdsale... will let you know when it's done.

**Comment by fernandomg** [comment]
@vbaranov I'm not able to create a crowdsale... now I got `Unexpected end of JSON input` (
[localhost-1515684799781.log](https://github.com/poanetwork/ico-wizard/files/1623129/localhost-1515684799781.log)


before that I managed to deploy all contracts, but got an error in https://github.com/poanetwork/ico-wizard/blob/e5939c2492daae88f792a3e7dc15540328da00f7/src/components/stepFour/utils.js#L287
with `reduce is not a function`

...

**Comment by vbaranov** [comment]
@fernandomg is registry contract address for mainnet in your `.env`?

**Comment by fernandomg** [comment]
> @fernandomg is registry contract address for mainnet in your .env?

@vbaranov yes

----
Ah, and in the first try I got a **Failed to fetch** error on the `error` event, so I did a slight change to consider both cases (_Failed to fetch_ and _Failed to check for transaction receipt_):

```javascript
let sendTX = (method, type) => {
// [...]
      .on('error', error => {
// [...]
        if (!error.message.includes('Failed to check for transaction receipt') && !error.message.includes('Failed to fetch')) reject(error)
      })
      .on('transactionHash', _txHash => checkTxMined(_txHash, function pollingReceiptCheck (err, receipt) {
// [...]
        if (err && !err.message.includes('Failed to check for transaction receipt') && !err.message.includes('Failed to fetch')) return reject(err)
// [...]
```

**Comment by vbaranov** [comment]
Ok. I'm gonna to skip this error `Unexpected end of JSON input` too. @fernandomg is the last transaction, which caused this error mined successfully?

**Comment by fernandomg** [comment]
> is the last transaction, which caused this error, mined successfully?

@vbaranov , yes: https://etherscan.io/tx/0x510f53f9400d3577c0c6319389710f1e88ff987a136c63074e11fde0809f8fbc

**Comment by vbaranov** [comment]
@fernandomg I've updated PR with skipping `Unexpected end of JSON input` error in both events `error` and `transactionHash`. Do we still have here something unhandled for mainnet?

**Comment by fernandomg** [comment]
@vbaranov I think not. I'm running out of `eth` to keep testing, so I it's working fine to you, I'll approve it.

**Comment by vbaranov** [comment]
@fernandomg I don't see more issues. Please approve.

**Pull request merged**
