### PR TITLE
(Feature) Change Whitelist Disabled to Whitelist Enabled

### LINKED ISSUE #440: (Feature) Change "Disable whitelisting" (defaulted to Yes) to "Enable whitelisting" (defaulted to No)
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

All

### If you were able to create it, what is the URL of your crowdsale?

Not related

### Do you have screenshots showing the problem?

image

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

No

---

### PR DESCRIPTION
**Pull request by fernandomg**
Closes #440

### CODE REVIEW

**Comment by fvictorio** [comment]
I'm getting an error trying to start the app in this branch:

```
Failed to compile
./src/components/manage/utils.js
  Line 247:  'whitelisted' is not defined  no-undef
```

**Comment by vbaranov** [comment]
@fvictorio I've updated current branch. Perhaps, the error is from manual conflicts resolving. There is shouldn't be this error now.

**Comment by fvictorio** [comment]
I can't properly test this because the invest is not working, see #498.

**Comment by fvictorio** [comment]
I changed the wording of the whitelist label. @vbaranov, if you think that's ok, please merge this.

**Pull request merged**
