### PR TITLE
(Feature) Use Oracle's API for Gas Price

### LINKED ISSUE #393: (Fix) Transaction underpriced
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Mainnet

### If you were able to create it, what is the URL of your crowdsale?

There is no crowdsale. Issue happens on the first transaction.

### Do you have screenshots showing the problem?

image

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

No

---

### PR DESCRIPTION
**Pull request by fernandomg**
Closes #393 

- Requests gas price on stepThree 
- Requests gas price for invest page
- If it's not able to reach the API's endpoint, it will display an alert with the message: _ICO Wizard wasn't able to request current Gas Prices from the blockchain, custom values will be used_

### CODE REVIEW

**Comment by igorbarinov** [comment]
Let's rename `Slow` to `Safe` in UI and make it default. 
People usually look for `safe` option on  in https://ethgasstation.info/ 
With the current price of Ethereum, it makes difference to use the cheapest version

@vbaranov what do you think?

**Comment by fernandomg** [comment]
@igorbarinov FYI, `invest` Tx uses the `Fast` price, shall I change it to `Safe` too?

**Comment by vbaranov** [comment]
Yes, 'Safe' sounds better than 'Slow'. And I agree with setting to the cheapest transactions by default everywhere in Wizard.

**Comment by fernandomg** [comment]
@igorbarinov @vbaranov changes done

**Comment by fernandomg** [comment]
@vbaranov You're right. It's unnecessary to consume the API for the testsnets.
But, in the other hand, I don't see the drawback of use it for the different testnets other than the amount of request done to the https://gasprice.poa.network endpoint

**Comment by rstormsf** [comment]
@fvictorio Looks great, however no tests :-( 
at least 1 test that goes thru main flow would really help

**Comment by vbaranov** [comment]
@rstormsf we could create tests in the background for this feature in a separate PR.
@fernandomg could you create a separate issue for oracle tests?
Relates to #461

**Pull request merged**
